// This file mirrors the auto-generated structure used by other Medium landing pages.
// In Medium, this would be generated by mono/ts/lite/src/app/codegen.

import {MainModule} from './MainModule'

export const LandingTkMarketingPage = {
  id: 'landing-tk-marketing',
  layoutConfig: {
    name: 'BasicLayout',
    lazyLoadingOptions: {shouldUseLoadableComponent: true},
  } as const,
  modules: {MainModule},
}
